### ISSUE TITLE
same sample, different result.

### ISSUE THREAD

**Issue by Leehyeonjin93** [xunchen85/ERVcaller#9]
hi,
I have human human samples and 2 computers.
I used a same sample on both computers.
but, results were different!
I used same options, programs(samtools, bwa, ERVcaller) version, reference.
additionally, I got error message when sample size over 61G.

> readline() on closed filehandle TAB at /home/super/Program/ERVcaller/ERVcaller_v1.4.pl line 1376.

This is my command.
`perl $ERV_path/ERVcaller_v1.4.pl -i $samplename -f .sorted.RGfixed.Rmdup.bam -H $refer -T $ERV_path/Database/Human_TE_library.fa -I $input_path/ -O $output_path/$samplename/ -r 150 -t 12 -S 40 -BWA_MEM -G `

* I ran multiple samples at the same time each screens.

**Comment by xunchen85** [comment]
Hi,

The results can be slightly different due to the alignment results (BWA) may not be exactly the same for each run. The running script was correct.  

I'm wondering if you can provide the complete log file? If the difference is significant, I would expect one of the two runs was not completed.

You may get the error messages if your computers did not have either memory or CPUs.

BTW, Samtools 1.5 can not be used as I indicated in the README file.

Best,
Xun

**Comment by Leehyeonjin93** [comment]
1. sorry, I didn't save log file. but some files' size  are different.

![image](https://user-images.githubusercontent.com/40356335/71452099-69c7da80-27c4-11ea-8cec-2bffa106d293.png)

![image](https://user-images.githubusercontent.com/40356335/71452079-53218380-27c4-11ea-97b4-9242a807c735.png)

I used bwa(0.7.12), samtools(1.9)  

2. This is computer' specification. isn't it enough?
![image](https://user-images.githubusercontent.com/40356335/71452204-f1621900-27c5-11ea-8016-bef0a37fb816.png)

thanks.

**Comment by xunchen85** [comment]
Hi,

The second run did not successfully complete with lots of temp files. It can be either because of the low specifications or not-successfully compiled ERVcaller on your second PC. 

BTW, do you have R installed in your second PC?

Best,
Xun

**Comment by Leehyeonjin93** [comment]
yes, second PC installed R, first too.
I will try to compile ERVcaller again.
I really want to know why super1 got error message.
I got error message both two computers. when sample size over 61G.
This are two computers' specification.

![](https://user-images.githubusercontent.com/40356335/71452204-f1621900-27c5-11ea-8016-bef0a37fb816.png)
![image](https://user-images.githubusercontent.com/40356335/71462569-0014f400-27f7-11ea-9d7a-039350d9ecaa.png)

**Comment by xunchen85** [comment]
Hi,

I have checked the script, and the error message is not related to sample size. Because the input of this line is tiny.

The error message tells that the ERVcaller can not load the file with the suffix of ".tab2" which was generated by the R script "Genotype_likelihood.R". Please check if you can run it using R command line: Rscript Scripts/Genotype_likelihood.R ${input_sampleID}.tab ${input_sampleID}.tab2. I also can send you a test data for it if you need.

Best,
Xun

**Comment by Leehyeonjin93** [comment]
yes,
when I got error message at first time, I tried that command.
It was worked. but, full perl scripts was not run.
so I tried to run process after R script step. But I can't fix perl scripts.

**Comment by xunchen85** [comment]
The error message indicated that ERVcaller cannot open ${input_sampleID}.tab file which was not removed by ERVcaller at that time. It may be because of either the sample size over your computer specification or an empty result. Without the log file, it is hard for me to help to debug. Thus, those are my suggestions:

1. run the test data to make sure the ERVcaller is correctly compiled;

2. if you can successfully run the test data without the error message, you can also try changing the name of test data to be the same as your input file in a new folder. It can exclude the naming issues after you run it.

3. if you can successfully run the test data without the error message, it means the issue is from your analyzed data. It is recommended to run your own sample with higher cpu or mem when analyzing samples with higher depth.

Best,
Xun

**Comment by Leehyeonjin93** [comment]
solution 1,2 was ok.
I will give up -G option to run ERV caller.
thanks...
